working_dir: &working_dir ~/app
version: 2.1
description: |
  An orb for working with Amazon Elastic Container Service (ECS)
  #######################################################################################
jobs:
  oo:
    
    docker:
      - image: cimg/node:19.2.0
    
    steps:
      - checkout
      - run:
          name: cu
          command: npm run test
  ooa:
    
    docker:
      - image: cimg/node:19.2.0
    
    steps:
      - checkout
      - run:
          name: cu
          command: npm run test
  oob:
    
    docker:
      - image: cimg/node:19.2.0
    
    steps:
      - checkout
      - run:
          name: cu
          command: npm run test
  ooc:
    
    docker:
      - image: cimg/node:19.2.0
    
    steps:
      - checkout
      - run:
          name: cu
          command: npm run test
  ood:
    
    docker:
      - image: cimg/node:19.2.0
    
    steps:
      - checkout
      - run:
          name: cu
          command: npm run test
  ooe:
    
    docker:
      - image: cimg/node:19.2.0
    
    steps:
      - checkout
      - run:
          name: cu
          command: npm run test
  oof:
    
    docker:
      - image: cimg/node:19.2.0
    
    steps:
      - checkout
      - run:
          name: cu
          command: npm run test
  oog:
    
    docker:
      - image: cimg/node:19.2.0
    
    steps:
      - checkout
      - run:
          name: cu
          command: npm run test
  ooh:
    
    docker:
      - image: cimg/node:19.2.0
    
    steps:
      - checkout
      - run:
          name: cu
          command: npm run test
  ooi:
    
    docker:
      - image: cimg/node:19.2.0
    
    steps:
      - checkout
      - run:
          name: cu
          command: npm run test

workflows:
  work:
    jobs:
      - oo
      - ooa
      - oob
      - ooc
      - ood
      - ooe
      - oof
      - oog
      - ooh
      - ooi

